package com.example.medicitas

import androidx.compose.runtime.staticCompositionLocalOf

enum class AppLanguage { ENG, ESP }

data class AppStrings(
    val greeting: String,
    val findDoctor: String,
    val specialOffer: String,
    val offerDesc: String,
    val bookNow: String,
    val departments: String,
    val seeAll: String,
    val popularDoctors: String,
    val searchDoctors: String,
    
    val appointments: String,
    val searchAppointment: String,
    val approved: String,
    val pending: String,
    val message: String,
    val callDoctor: String,
    val videoVisit: String,
    val inPerson: String,
    
    val reviewAndBook: String,
    val detailAppointment: String,
    val change: String,
    val event: String,
    val note: String,
    val addNote: String,
    val detailPatient: String,
    val whoIsPatient: String,
    val myself: String,
    val someone: String,
    val fullName: String,
    val phoneNumber: String,
    val newPatient: String,
    val insurance: String,
    val scanInsurance: String,
    val chooseManually: String,
    val officeLocation: String,
    val changeLocation: String,
    val termsAndConditions: String,
    val bookNowBtn: String,
    
    val appointmentDetail: String,
    val call: String,
    val schedule: String,
    val detail: String,
    val aboutAppointment: String,
    val appointmentChecklists: String,
    val completeForms: String,
    val uploadId: String,
    val minutes: String,
    val yourInsurance: String,
    val inNetwork: String,
    val insuranceType: String,
    val insuranceSubmitted: String,
    val guidelines: String,
    val thingsToKnow: String,
    val officeInfo: String,
    
    val bookAppointment: String,
    val morning: String,
    val afternoon: String,
    val evening: String,
    val makeAppointment: String,
    val appointmentFee: String,
    
    // Departments
    val deptBrain: String,
    val deptCardiology: String,
    val deptLung: String,
    val deptKidney: String,
    
    // Specialties
    val specPrimaryCare: String,
    val specDermatologist: String,
    val specCardiologist: String,
    val specEye: String,
    
    // Doctor Names (Latin)
    val drMendoza: String,
    val drMartinez: String,
    val drRodriguez: String,
    val drLopez: String,
    
    // Patient
    val patientName: String,

    // Navigation
    val navHome: String,
    val navBook: String,
    val navMyDoctor: String,
    val navChat: String,
    val navProfile: String,

    // Emergency Screen
    val navEmergencyLabel: String,
    val emergencyTitle: String,
    val requestAmbulance: String,
    val callEmergencies: String
)

val EnglishStrings = AppStrings(
    greeting = "Hi Freddy!",
    findDoctor = "Find a doctor easily",
    specialOffer = "SPECIAL OFFER",
    offerDesc = "Get a 35% discount on the first video consultation from now",
    bookNow = "Book Now",
    departments = "Departments",
    seeAll = "See All",
    popularDoctors = "Popular Doctors",
    searchDoctors = "Search Doctors",
    appointments = "Appointments",
    searchAppointment = "Search appointment",
    approved = "Approved",
    pending = "Pending Confirmation",
    message = "Message",
    callDoctor = "Call doctor",
    videoVisit = "Video Visit",
    inPerson = "In Person",
    reviewAndBook = "Review and Book",
    detailAppointment = "Detail appointment",
    change = "Change",
    event = "Event",
    note = "Note",
    addNote = "Add note for doctor",
    detailPatient = "Detail patient",
    whoIsPatient = "Who's the patient",
    myself = "Myself",
    someone = "Someone",
    fullName = "Full name",
    phoneNumber = "Phone number",
    newPatient = "I'm a new patient",
    insurance = "Insurance",
    scanInsurance = "Scan insurance",
    chooseManually = "Choose manually",
    officeLocation = "Office Location",
    changeLocation = "Change location",
    termsAndConditions = "By proceeding, you agree to the Terms and Conditions and Privacy Policy of Medicitas.",
    bookNowBtn = "Book now",
    appointmentDetail = "Appointment Detail",
    call = "Call",
    schedule = "Schedule",
    detail = "Detail",
    aboutAppointment = "About appointment",
    appointmentChecklists = "Appointment checklists",
    completeForms = "Complete forms",
    uploadId = "Upload your ID card",
    minutes = "3-4 Minute",
    yourInsurance = "Your insurance",
    inNetwork = "In-Network with Medicare",
    insuranceType = "Original Medicare Part A&B",
    insuranceSubmitted = "Your insurance information has been submitted to your provider for verification.",
    guidelines = "Guidelines for patients",
    thingsToKnow = "Things you should know before you arrive",
    officeInfo = "Office Information",
    bookAppointment = "Book appointment",
    morning = "Morning",
    afternoon = "Afternoon",
    evening = "Evening",
    makeAppointment = "Make appointment",
    appointmentFee = "Appointment Fee:",
    
    deptBrain = "Brain",
    deptCardiology = "Cardiology",
    deptLung = "Lung",
    deptKidney = "Kidney",
    
    specPrimaryCare = "Primary care doctor",
    specDermatologist = "Dermatologist Specialist",
    specCardiologist = "Cardiologist Specialist",
    specEye = "Eye Specialist",
    
    drMendoza = "Dr. Alejandro Mendoza",
    drMartinez = "Dr. Carlos Martínez",
    drRodriguez = "Dra. Sofía Rodríguez",
    drLopez = "Dr. Jacob Lopez",
    
    patientName = "Freddy",

    navHome = "Home",
    navBook = "Book",
    navMyDoctor = "My doctor",
    navChat = "Chat",
    navProfile = "Profile",

    navEmergencyLabel = "Emergency",
    emergencyTitle = "Emergency Actions",
    requestAmbulance = "Request an ambulance",
    callEmergencies = "Call emergencies"
)

val SpanishStrings = AppStrings(
    greeting = "¡Hola Freddy!",
    findDoctor = "Encuentra un doctor fácilmente",
    specialOffer = "OFERTA ESPECIAL",
    offerDesc = "Obtén un 35% de descuento en la primera video consulta desde ahora",
    bookNow = "Reservar Ahora",
    departments = "Departamentos",
    seeAll = "Ver Todo",
    popularDoctors = "Doctores Populares",
    searchDoctors = "Buscar Doctores",
    appointments = "Citas",
    searchAppointment = "Buscar cita",
    approved = "Aprobada",
    pending = "Pendiente de Confirmación",
    message = "Mensaje",
    callDoctor = "Llamar doctor",
    videoVisit = "Video Consulta",
    inPerson = "Presencial",
    reviewAndBook = "Revisar y Reservar",
    detailAppointment = "Detalle de la cita",
    change = "Cambiar",
    event = "Evento",
    note = "Nota",
    addNote = "Añadir nota para el doctor",
    detailPatient = "Detalle del paciente",
    whoIsPatient = "¿Quién es el paciente?",
    myself = "Yo mismo",
    someone = "Alguien más",
    fullName = "Nombre completo",
    phoneNumber = "Número de teléfono",
    newPatient = "Soy un paciente nuevo",
    insurance = "Seguro",
    scanInsurance = "Escanear seguro",
    chooseManually = "Elegir manualmente",
    officeLocation = "Ubicación de la oficina",
    changeLocation = "Cambiar ubicación",
    termsAndConditions = "Al continuar, aceptas los Términos y Condiciones y la Política de Privacidad de Medicitas.",
    bookNowBtn = "Reservar ahora",
    appointmentDetail = "Detalle de la Cita",
    call = "Llamar",
    schedule = "Agenda",
    detail = "Detalle",
    aboutAppointment = "Sobre la cita",
    appointmentChecklists = "Listas de verificación de la cita",
    completeForms = "Completar formularios",
    uploadId = "Subir tarjeta de identificación",
    minutes = "3-4 Minutos",
    yourInsurance = "Tu seguro",
    inNetwork = "En red con Medicare",
    insuranceType = "Medicare Original Parte A y B",
    insuranceSubmitted = "La información de su seguro ha sido enviada a su proveedor para su verificación.",
    guidelines = "Guía para pacientes",
    thingsToKnow = "Cosas que debe saber antes de llegar",
    officeInfo = "Información de la Oficina",
    bookAppointment = "Reservar cita",
    morning = "Mañana",
    afternoon = "Tarde",
    evening = "Noche",
    makeAppointment = "Programar cita",
    appointmentFee = "Costo de la Cita:",
    
    deptBrain = "Cerebro",
    deptCardiology = "Cardiología",
    deptLung = "Pulmón",
    deptKidney = "Riñón",
    
    specPrimaryCare = "Médico de atención primaria",
    specDermatologist = "Especialista en Dermatología",
    specCardiologist = "Especialista en Cardiología",
    specEye = "Especialista de Ojos",
    
    drMendoza = "Dr. Alejandro Mendoza",
    drMartinez = "Dr. Carlos Martínez",
    drRodriguez = "Dra. Sofía Rodríguez",
    drLopez = "Dr. Jacob Lopez",
    
    patientName = "Freddy",

    navHome = "Inicio",
    navBook = "Reservar",
    navMyDoctor = "Mi doctor",
    navChat = "Chat",
    navProfile = "Perfil",

    navEmergencyLabel = "Emergencia",
    emergencyTitle = "Acciones de Emergencia",
    requestAmbulance = "Solicitar una ambulancia",
    callEmergencies = "Llamar a emergencias"
)

val LocalStrings = staticCompositionLocalOf { EnglishStrings }
